import { Prisma } from "@prismagen/client";
import * as db from "@lib/db-seed";
import { Classes, Continents, CreatureSizes, CreatureTypes, Deities, Languages, Races, Subclasses, Subraces, Towns } from "./index";

type CharacterPayload = Prisma.CharacterGetPayload<{}>;
export interface Characters {
	tharosRaggenthraw: CharacterPayload;
	kinrisMorranfew: CharacterPayload;
	ovlanKalek: CharacterPayload;
	varonTavis: CharacterPayload;
	caelumRiversong: CharacterPayload;
	rishaSwiftdancer: CharacterPayload;
	lemunSilverflock: CharacterPayload;
	bolagorBonejaw: CharacterPayload;
	jadeClearrock: CharacterPayload;
	ilikanWildfist: CharacterPayload;
	aurenWildfist: CharacterPayload;
	keotiFang: CharacterPayload;
	snekLittlefoot: CharacterPayload;
	fionaWildfist: CharacterPayload;
	whoWingfall: CharacterPayload;
	xandrosKirvath: CharacterPayload;
	verdiSapKnot: CharacterPayload;
	krakFrostmarchCompany: CharacterPayload;
	sabaakFrostmarchCompany: CharacterPayload;
	varkunTarlok: CharacterPayload;
	whisper: CharacterPayload;
    elaraMoonwhisper: CharacterPayload;
    gorakSwampstrider: CharacterPayload;
    thorneIronforge: CharacterPayload;
    bronwynStonebeard: CharacterPayload;
    marcusGoldfield: CharacterPayload;
    thaneIcewind: CharacterPayload;
}

interface SeedCharactersParams {
    races: Races
    subraces: Subraces
    classes: Classes
    subclasses: Subclasses
    languages: Languages
    deities: Deities
    continents: Continents
    towns: Towns
    creatureSizes: CreatureSizes
    creatureTypes: CreatureTypes
}
export async function seedCharacters(params: SeedCharactersParams): Promise<Characters> {
    const { races, subraces, classes, subclasses, languages, deities, continents, towns, creatureSizes, creatureTypes } = params;
    return {
		tharosRaggenthraw: await db.createCharacter({
            id: 'character-tharos-raggenthraw',
			name: 'Tharos Raggenthraw',
			raceId: races.leonin.id,
			classId: classes.cleric.id,
			subclassId: subclasses.cleric_war_domain.id,
            backstory: "Former veteran of the Skratonian Alliance's military forces who founded the guild after witnessing villages abandoned to monsters while soldiers fought foreign wars. The legendary wyvern slayer who established the guild's core values and continues to lead by example. Tharos's leadership philosophy embraces the idea that those risking their lives in the field should determine their own methods, so long as they serve the greater good of protecting the innocent. This pragmatic approach allows the guild to welcome diverse alignments and fighting styles while maintaining unity of purpose.",
			gender: 'Male',
            appearance: "A barrel-chested leonin with a thick dark mane streaked with silver. His face bears a scar across the muzzle and cheek, a mark of his legendary duel with a wyvern. He wears deep-blue mithral plate and wields Ruinbreaker, a massive greataxe etched with divine runes.",
            personality: "Equal parts father-figure and commander. Stern when needed, but known for his booming laugh and ability to unite wildly different adventurers under one cause.",
            keyAttributes: 'His unwavering dedication to protecting the innocent and his strategic mind in battle.',
            ideals: "Protection: Those who can fight have a duty to protect the innocent, even at great personal risk.",
            age: 95,
            bonds: "The Huntbound Guild: Tharos's greatest pride and responsibility, seeing it grow from a small band of adventurers to a renowned force for good.",
            flaws: "Leniency: Sometimes too trusting of others' intentions, believing in redemption even for those with dark pasts.",
            gearLoadout: "Wields Ruinbreaker, a massive greataxe etched with divine runes. Wears deep-blue mithral plate armor.",
            languages: {
				connect: [
					{ id: languages.common.id },
					{ id: languages.leonin.id },
                    { id: languages.common_sign_language.id },
				],
			},
			deityId: deities.tempus.id,
			deityReasoning:
				'As a War Domain Cleric and founder of the Huntbound Order, Tharos follows Tempus, the Lord of Battles, who represents honor, strategy, and the glory of combat.',
            fromContinentId: continents.skratonia.id,
            livesInTownId: towns.suetonon.id,
            creatureSizeId: creatureSizes.medium.id,
            creatureTypeId: creatureTypes.humanoid.id,
		}),
		kinrisMorranfew: await db.createCharacter({
            id: 'character-kinris-morranfew',
            name: 'Kinris Morranfew',
            raceId: races.kalashtar.id,
            classId: classes.tactician.id,
            subclassId: subclasses.tactician_mentalist.id,
            backstory: "Born to a wandering caravan, Kinris found her place among The Huntbound Order as much for her wit and brewing as for her healing touch. She became the guild's unofficial heart: tending wounds, pouring drinks, and listening to the burdens of hunters who return from bloody work. Though she avoids killing, her strategic mind aids guild hunts with clever plans and mentalist insight. To many members, Kinris is both a sister and a counselor — the keeper of secrets, scars, and spirits (both strong drink and soulful guidance).",
            gender: 'Female',
            appearance: "A warm-eyed Kalashtar woman of 26 years, with intricate black tattoos swirling across her face and arms. She keeps her dark hair in a thick braid over her shoulder and wears a blue tunic beneath a leather apron. Her hands are calloused from both brewing and healing, and her ever-present smile carries both mischief and kindness.",
            personality: "Lively, compassionate, and endlessly curious about others. Kinris does everything with flair, often too much, but her energy is infectious. She listens deeply, makes everyone feel heard, and believes even the most broken soul can be mended with patience, laughter, and care.",
            deityId: deities.tempus.id,
            deityReasoning:
                "Respects Tempus's blessing on the guild, but her personal philosophy is rooted in the sanctity of life and quiet compassion over divine wrath.",
            age: 26,
            keyAttributes: "Her empathy and ability to read people, combined with a sharp strategic mind honed through years of guild service.",
            ideals: "Compassion: Every life is precious, and healing is as vital as fighting.",
            bonds: "The Huntbound Guild: Kinris is deeply committed to the guild's members, seeing them as family and dedicating herself to their well-being.",
            flaws: "Tactlessness: Her blunt honesty and playful teasing can sometimes offend those who don't know her well.",
            gearLoadout: "Always carries a satchel of herbal remedies, a set of artisan brewing tools, and a finely crafted dagger for protection.",
            languages: {
                connect: [
                    { id: languages.common.id },
                    { id: languages.telepathic.id },
                ],
            },
            fromContinentId: continents.kuriguer.id,
            livesInTownId: towns.suetonon.id,
            creatureSizeId: creatureSizes.medium.id,
            creatureTypeId: creatureTypes.humanoid.id,
        }),
		ovlanKalek: await db.createCharacter({
            id: 'character-ovlan-kalek',
            name: 'Ovlan Kalek',
            raceId: races.vedalken.id,
            classId: classes.wizard.id,
            subclassId: subclasses.wizard_order_of_scribes.id,
            backstory: "Once a youth of the Witchlight Carnival, Ovlan left its endless cycle of revelry when it lost its wonder, seeking greater meaning in study and service. He found the Huntbound Order suited his desires, and adventured for the Guild for many years, making his way up to Silver rank.Now he serves as the Huntbound Order's librarian, with an uncanny memory for where every book lies. He aids hunters not by blade but by insight, scribing records of their deeds and providing arcane knowledge crucial for their survival, recently publishing a collection of his findings through research and experience in his 'Monster Slayers Guide'. With his wisp companion ever at his side, he embodies the Order's bond of camaraderie — a friend who would never leave another behind.",
            gender: 'Male',
            appearance: "A blue-skinned Vedalken male of 55 years, with sharp features, pale eyes that seem almost without pupils, and intricate black tattoos curling across his bald head. He wears deep silver robes trimmed in blue, and carries both a staff crowned with a glowing orb and a well-worn tome. His movements are precise, though he often appears distracted as if caught in thought.",
            personality: "Thoughtful, eccentric, and prone to losing track of time. Ovlan has a passion for knowledge and the written word, speaking with excitement when inspiration strikes. He is kind-hearted, though absentminded, and has a habit of weeping at moving music. His friends know him as dependable, if always late.",
            deityId: deities.tempus.id,
            deityReasoning:
                "While he holds no personal god, he honors the War God Tempus as patron of the Huntbound Order, treating divine blessing with quiet respect rather than devotion.",
            age: 55,
            keyAttributes: "His vast knowledge of monsters and arcane lore, combined with a meticulous memory and scholarly approach to problems.",
            ideals: "Knowledge: Understanding the world and its creatures is the key to survival and success.",
            bonds: "The Huntbound Guild: Ovlan is deeply committed to the guild's mission and its members, seeing them as both subjects of study and friends.",
            flaws: "Absentmindedness: His tendency to get lost in thought can lead to forgetfulness and social awkwardness.",
            gearLoadout: "Carries a staff crowned with a glowing orb, a well-worn tome filled with notes and sketches, and various arcane trinkets collected from his adventures.",
            languages: {
                connect: [
                    { id: languages.common.id },
                    { id: languages.goblin.id },
                    { id: languages.vedalken.id },
                    { id: languages.primordial.id },
                ],
            },
            fromContinentId: continents.skratonia.id,
            livesInTownId: towns.suetonon.id,
            creatureSizeId: creatureSizes.medium.id,
            creatureTypeId: creatureTypes.humanoid.id,
        }),
		varonTavis: await db.createCharacter({
            id: 'character-varon-tavis',
            name: 'Varon Tavis',
            raceId: races.hobgoblin.id,
            classId: classes.barbarian.id,
            subclassId: subclasses.barbarian_path_of_the_totem_warrior.id,
            backstory: "Exiled from his clan for reasons he rarely speaks of, Varon carved out a life as an outlander, living by strength, grit, and knowledge of the land. His exile turned to belonging when he joined the Huntbound Order, where his tracking skill, endurance, and raw might found new purpose. Yet his truest gift lies in the forge: Varon serves as the guild's blacksmith and smithing trainer, shaping weapons and armor that carry Huntbound hunters into battle. The clang of his hammer is as constant as the roar of beasts on the hunt, and his forge is open to any guildmate seeking to learn. Though quiet and guarded, he is a steadfast companion on the hunt and a shield for those he calls kin.",
            gender: 'Male',
            appearance: "A tall, broad-shouldered Hobgoblin of 36 years, standing six feet tall with weathered, battle-marked red skin. His sharp features carry the stern intensity of one who has lived long in the wilds. He wears furs, leathers, and a blacksmith's apron of blue and silver. His arms are corded with muscle from years at the anvil, and his hands are scarred, calloused, and blackened from the forge.",
            personality: "Blunt, wary, and slow to trust outsiders, Varon respects strength and survival above all. Though not cruel, he has little patience for wealth or refinement, believing only experience in the wild proves worth. Once his trust is earned, however, his loyalty is unwavering, rooted in clan bonds and hard-earned camaraderie. He takes pride in teaching others the craft of smithing, seeing the forge as both a crucible and a bond between warriors.",
            deityReasoning:
                "He holds no faith in gods, but honors the strength of the wilds, storms, and mountains as forces that shape all beings.",
            age: 36,
            keyAttributes: "His physical strength, endurance, and skill in both tracking and blacksmithing.",
            ideals: "Strength: Only the strong survive in the wilds; strength is earned through hardship and battle.",
            bonds: "The Huntbound Guild: Varon values the guild as a surrogate clan, finding belonging among those who share his respect for strength and survival.",
            flaws: "Distrustful: His exile has left him wary of outsiders, making it difficult for him to form new bonds.",
            gearLoadout: "Wields a massive hammer forged in his own smithy, wears sturdy furs and leathers, and carries a set of blacksmithing tools.",
            languages: {
                connect: [
                    { id: languages.common.id },
                    { id: languages.goblin.id },
                    { id: languages.giant.id },
                ],
            },
            fromContinentId: continents.bulsania.id,
            livesInTownId: towns.suetonon.id,
            creatureSizeId: creatureSizes.medium.id,
            creatureTypeId: creatureTypes.humanoid.id,
        }),
		caelumRiversong: await db.createCharacter({
            id: 'character-caelum-riversong',
            name: 'Caelum Riversong',
            raceId: races.half_elf.id,
            subraceId: subraces.half_elf_wood_half_elf.id,
            classId: classes.cleric.id,
            subclassId: subclasses.cleric_life_domain.id,
            backstory: "The son of a wood elf father and a human mother from a proud artisan family, Caelum was trained as an apothecary and healer under his guild's guidance. Skilled in alchemy, remedies, and clerical healing, he became the guild's Doctor — tending wounds with both divine grace and crafted remedies. His perfectionism sometimes makes him linger over details, but his steady hands and steady heart have saved many lives. To his fellow guild members, Caelum is both a healer of the body and a quiet anchor of community.",
            gender: 'Male',
            appearance: "A 28-year-old half-elf man with warm brown skin, angular features softened by his human heritage, and dark, tightly curled hair often pushed back beneath a pair of spectacles. He is nimble in well-worn leather armor, his hands steady and precise from years of apothecary work. Though scholarly in demeanor, there is an alert sharpness to his movements that hints at both discipline and care.",
            personality: "Meticulous, thoughtful, and quietly compassionate. Caelum is a perfectionist who holds himself to the highest standards, especially in his healing craft. While often serious, he carries a dry wit and deep patience that put others at ease. He believes in community, care, and the quiet strength of doing things properly.",
            deityId: deities.lathander.id,
            deityReasoning:
                "A devoted follower of Lathander, god of dawn, renewal, and vitality. Caelum sees each life saved as a chance for rebirth and believes healing is a sacred act of honoring new beginnings.",
            age: 28,
            keyAttributes: "His skill in healing, both divine and alchemical, combined with a meticulous and caring approach to his work.",
            ideals: "Compassion: Every life is precious, and healing is a sacred duty.",
            bonds: "The Huntbound Guild: Caelum is deeply committed to the guild's members, seeing them as family and dedicating himself to their well-being.",
            flaws: "Perfectionism: His high standards can lead to overthinking and hesitation, especially in high-pressure situations.",
            gearLoadout: "Carries a satchel filled with alchemical supplies, healing potions, and a well-used set of surgical tools.",
            languages: {
                connect: [
                    { id: languages.common.id },
                    { id: languages.elvish.id },
                    { id: languages.common_sign_language.id },
                ],
            },
            fromContinentId: continents.kuriguer.id,
            livesInTownId: towns.suetonon.id,
            creatureSizeId: creatureSizes.medium.id,
            creatureTypeId: creatureTypes.humanoid.id,
        }),
		rishaSwiftdancer: await db.createCharacter({
            id: 'character-risha-swiftdancer',
            name: 'Risha Swiftdancer',
            raceId: races.hadozee.id,
            classId: classes.artificer.id,
            subclassId: subclasses.artificer_armorer.id,
            backstory: "Once a criminal and fence in the underworld, Risha made her name by stealing, tinkering, and reselling goods with clever improvements. Her reckless streak nearly ended at the gallows until the guildmaster himself spared her life after she stole and modified his greataxe, impressing him enough to grant her a place in the guild. Now serving as the guild's artificer and black-market contact, she repays her old debt through loyalty and craft, while never quite losing the chaotic spark that first carried her into trouble.",
            gender: 'Female',
            appearance: "A wiry Hadozee woman in her early 30s, with sharp eyes that dart constantly as if always calculating. Her fur is dark and unkempt, often streaked with soot and grease from her tinkering. She wears studded leather armor hidden beneath a patched and scorched apron, with belts full of tools and trinkets jangling at her sides. Her quick hands and restless stance give the impression of someone always ready to steal, fix, or break something.",
            personality: "Defiant, hot-tempered, and fiercely loyal to those she calls friends. Risha thrives on proving others wrong and takes insults personally, often lashing out in bursts of temper. She has little patience for plans or authority, preferring to improvise and follow her instincts. Despite her criminal past, she values bonds of loyalty above all else and will fight tooth and claw for those she owes her trust.",
            deityReasoning:
                "Not particularly devout. Risha places her faith in her skills, her tools, and the guild that gave her a second chance.",
            age: 32,
            keyAttributes: "Her ingenuity, quick reflexes, and skill in tinkering and improvisation.",
            ideals: "Freedom: No one controls Risha; she answers only to herself and those she trusts.",
            bonds: "The Huntbound Guild: Risha is fiercely loyal to the guild, seeing it as her second chance and repaying her debt through service and craft.",
            flaws: "Quick-Tempered: Her fiery temper can lead to rash decisions and conflicts, especially when she feels disrespected.",
            gearLoadout: "Carries a variety of tinkering tools, improvised gadgets, and a modified set of thieves' tools.",
            languages: {
                connect: [
                    { id: languages.common.id },
                    { id: languages.hadozee.id },
                    { id: languages.undercommon.id },
                ],
            },
            fromContinentId: continents.skratonia.id,
            livesInTownId: towns.suetonon.id,
            creatureSizeId: creatureSizes.medium.id,
            creatureTypeId: creatureTypes.humanoid.id,
        }),
		lemunSilverflock: await db.createCharacter({
            id: 'character-lemun-silverflock',
            name: 'Lemun Silverflock',
            raceId: races.aasimar.id,
            subraceId: subraces.aasimar_protector_aasimar.id,
            classId: classes.fighter.id,
            backstory: "Lumen was only eight years old when his village was attacked and burned by a horde of goblins, leaving his parents dead. Hiding alone among the ruins for days, he was eventually found by a Huntbound Order guild party sent to investigate. They rescued him, and while accompanying them he learned much about goblins and their ways. Taken back to the guild hall, he was given the rank of Copper with the understanding that he would serve, train, and grow within the guild until he could properly take up the adventuring mantle. Now, at 11 years old, Lumen works as the guild's butler — tending to the hall, helping with chores, and assisting the members as needed. He has manager to convince the Guild's House Carl Keoti, to oversee much of his training, although taking tips and pointers from all manner of warriors in the guild. Though still young, he has already shown a fierce devotion to justice and carries within him the promise of a protector destined to rise.",
            gender: 'Male',
            appearance: "An 11-year-old boy with pale skin touched by a faint celestial glow, silver-white hair that falls into his eyes, and wings that only flicker into view when he is deeply moved or frightened. His eyes are a soft gray, carrying the weight of grief beyond his years. He wears plain but well-kept shirt with a brown leather vest, and keeps a wooden practice sword at his side wherever he goes.",
            personality: "Quiet but determined, Lumen carries himself with a sense of responsibility rare for his age. The loss of his family has made him mature quickly, but underneath his stoic front lies the heart of a child who still longs for safety and belonging. He has developed a strong sense of justice and fairness, sometimes stubbornly so, and looks up to the guild members as both mentors and surrogate family.",
            deityId: deities.kelemvor.id,
            deityReasoning:
                "Having studied in the guild's temple and learned from many members' different devotions, Lumen chose to follow Kelemvor, Lord of the Dead and Justice. He prays to him not only for the safe passage of souls, but for the strength to ensure justice for the living and the fallen. His faith is quiet but resolute, rooted in the belief that death should be honored and justice always served.",
            age: 11,
            keyAttributes: "His unwavering sense of justice, determination to protect others, and quick learning ability despite his youth.",
            ideals: "Justice: Every action has consequences, and it is our duty to ensure fairness and protect the innocent.",
            bonds: "The Huntbound Guild: Lumen sees the guild as his new family and is deeply committed to serving and protecting its members.",
            flaws: "Stubbornness: His strong sense of justice can lead to inflexibility and difficulty accepting others' viewpoints.",
            gearLoadout: "A simple wooden practice sword, a small shield emblazoned with the Huntbound emblem, and a satchel containing basic supplies and a journal.",
            languages: {
                connect: [
                    { id: languages.common.id },
                    { id: languages.celestial.id },
                    { id: languages.tabaxi.id },
                ],
            },
            fromContinentId: continents.skratonia.id,
            livesInTownId: towns.suetonon.id,
            creatureSizeId: creatureSizes.medium.id,
            creatureTypeId: creatureTypes.humanoid.id,
        }),
		bolagorBonejaw: await db.createCharacter({
            id: 'character-bolagor-bonejaw',
            name: 'Bolagor Bonejaw',
            raceId: races.orc.id,
            classId: classes.bard.id,
            subclassId: subclasses.bard_college_of_lore.id,
            backstory: "Born into the mercantile circles of artisans, Bolagor trained under a master cook in his youth, learning both the art of food and the art of negotiation. The workshop where he apprenticed remains sacred to him, a place he believes forged his identity. Never content to settle, he sought greater purpose beyond simple trade, eventually finding a place within the Huntbound Order. There, he became the guild's cook and negotiator, ensuring not only that the members are well-fed but also that their supplies and expenses are managed with keen efficiency. Though gruff with his coin, he is ultimately generous, viewing his skills as gifts meant to benefit the world. He is known among the guild as a man who can turn the humblest of rations into feasts and the harshest of merchants into allies.",
            gender: 'Male',
            appearance: "A towering orc of 48 years, standing 6'4” and weighing 235 pounds, with broad shoulders and a strong frame built from years in the kitchen. His tusks are slightly worn, and one bears a small chip from a long-forgotten scuffle. His skin is a muted green-gray, marked with faint scars, and his black hair is kept shaved close to the scalp for practicality. His deep-set eyes gleam with shrewd intelligence. He typically wears a heavy apron, with knives and spice pouches hanging from his belt like weapons of his trade.",
            personality: "Gruff but generous, Bolagor has a practical nature shaped by years of hard work. He is stubborn when it comes to coin and haggles relentlessly, yet he does so for the good of the guild rather than selfish gain. Despite his grumbling tone, he takes pride in feeding the Huntbound Order and making sure they are never short of supplies. He enjoys telling exaggerated tales of culinary duels and merchant bargains won, often to entertain the younger members of the hall.",
            deityReasoning:
                "Bolagor follows no god, placing his trust instead in skill, hard work, and the bonds of his guild. He respects faith in others but sees his craft and cleverness as his guiding lights.",
            age: 48,
            keyAttributes: "His culinary skill, shrewd negotiation tactics, and unwavering dedication to the guild's well-being.",
            ideals: "Fairness: No belly should go hungry, and no deal should be made without careful thought and negotiation.",
            bonds: "The Huntbound Guild: Bolagor is deeply committed to the guild's members, seeing them as family and dedicating himself to their sustenance and success.",
            flaws: "Stubbornness: His practical nature can lead to inflexibility, especially when it comes to money and negotiations.",
            gearLoadout: "A set of finely crafted cooking knives, a spice pouch filled with exotic seasonings, and a ledger for tracking supplies and expenses.",
            languages: {
                connect: [
                    { id: languages.common.id },
                    { id: languages.orcish.id },
                    { id: languages.halfling.id },
                    { id: languages.yuan_ti.id },
                    { id: languages.elvish.id },
                ],
            },
            fromContinentId: continents.katman.id,
            livesInTownId: towns.suetonon.id,
            creatureSizeId: creatureSizes.medium.id,
            creatureTypeId: creatureTypes.humanoid.id,
        }),
		jadeClearrock: await db.createCharacter({
            id: 'character-jade-clearrock',
            name: 'Jade Clearrock',
            raceId: races.dragonborn.id,
            subraceId: subraces.dragonborn_gem_dragonborn.id,
            classId: classes.warlock.id,
            subclassId: subclasses.warlock_the_archfey.id,
            backstory: "Jade began her life in the shadows, working as a spy and blackmailer, dealing in secrets and political leverage. However, the constant web of lies and danger grew wearisome, and Jade sought a new path. Leaving espionage behind, she joined the Huntbound Order, turning her skills toward adventuring and monster hunting. It was during this period that Jade formed a pact with an Archfey patron, honing her powers as a warlock. Age and experience, however, eventually led Jade to retire from field work. With retirement came the dissolution of her fey contract, the bond fading as she stepped away from the life of quests and combat. Now, Jade serves the Huntbound Order as its quest receptionist and records keeper, managing missions, tracking reports, and ensuring the guild's operations run with precision. Though no longer wielding eldritch power, Jade's sharp mind, calm demeanor, and gift for subtle persuasion make her just as valuable as ever.",
            gender: 'Female',
            appearance: "An Emerald gem dragonborn whose crystalline scales shimmer in hues of green and silver under the light, giving her a calm and commanding presence. Her features are sharp and refined, often softened by a faint, knowing smile. Though age has dulled some of Her vibrancy, Her movements remain deliberate and graceful. Her attire is well-kept yet practical: layered robes with subtle embroidery, a ledger always in hand, and a faint scent of ink and herbs lingering about her.",
            personality: "Unflappable and composed, Jade is known for remaining calm in even the most chaotic situations. her voice is measured, never raised, and she prefer diplomacy over confrontation. A natural negotiator, Jade has a knack for turning potential conflict into cooperation. She are kind but guarded, and though her past is filled with shadows, she now channel her sharp wit and keen perception into keeping the Huntbound Order running smoothly.",
            deityId: deities.tymora.id,
            deityReasoning:
                "Jade places her faith in Tymora, Lady Luck. Once a patron prayed to in secrecy before dangerous missions, Tymora is now a source of comfort and guidance in Jade's retirement, representing the risks and chances that shaped her life.",
            age: 62,
            keyAttributes: "Her keen intellect, diplomatic skills, and ability to manage complex operations with grace.",
            ideals: "Balance: Every action has its consequences, and it is essential to maintain harmony in all things.",
            bonds: "The Huntbound Guild: Jade is deeply committed to the guild's success, seeing it as her legacy and dedicating herself to its smooth operation.",
            flaws: "Cautiousness: Her past has made her wary of trust, leading to hesitation in forming new relationships.",
            gearLoadout: "A well-worn ledger, a quill and ink set, and a small charm of Tymora for luck.",
            languages: {
                connect: [
                    { id: languages.common.id },
                    { id: languages.draconic.id },
                    { id: languages.elvish.id },
                    { id: languages.goblin.id },
                    { id: languages.undercommon.id },
                    { id: languages.halfling.id },
                    { id: languages.thri_kreen.id },
                    { id: languages.hadozee.id },
                    { id: languages.orcish.id}
                ],
            },
            fromContinentId: continents.bulsania.id,
            livesInTownId: towns.suetonon.id,
            creatureSizeId: creatureSizes.medium.id,
            creatureTypeId: creatureTypes.humanoid.id,
        }),
		fionaWildfist: await db.createCharacter({
            id: 'character-fiona-wildfist',
            name: 'Fiona Wildfist',
            raceId: races.changeling.id,
            classId: classes.ranger.id,
            subclassId: subclasses.ranger_drakewarden.id,
            backstory: "Born in the forests of Kuriguer, Fiona remembers little of her earliest years before becoming separated from her kin. She was raised for a time by a band of druids until a fateful encounter with a wild beast forced her into a cavern where she discovered an ancient standing stone marked with draconic runes. Touching it bound draconic power to her forever, awakening her bond with a drake. For years she survived in the forests alone, guided by both Fey whispers and her newfound draconic strength, until she finally gathered the courage to journey into cities. There she lived as a ranger, selling her skills and slowly making her way across the land. Eventually, Fiona joined the Huntbound Order, where her knowledge of beasts and survival proved invaluable on countless quests. During her time adventuring, she fell in love with the guild's groundskeeper Ilikan, and after marrying and giving birth to their son, she chose to retire from the dangerous life of quests. For the past nine years, Fiona has served as the Huntbound Order's seeded Beast Master, tending to the guild's mounts, companions, and familiars. With her drake at her side and a heart still tied to both the Feywild and her draconic blessing, she is a constant presence of care, guidance, and wonder within the guild.",
            gender: 'Female',
            appearance: "A changeling of 34 years, Fiona's features often favor a form with soft silver hair with a fiery braid, pale moonlit skin speckled with scales, and bright eyes that reflect her bond to the Feywild. She stands 5'4” with a wiry frame honed by years of surviving the wilds. Her drake companion, a scaled creature of amber and silver hues, is never far from her side. She dresses in practical ranger garb, accented with charms of feathers, bone, and silver jewelry dedicated to Selûne.",
            personality: "Whimsical yet grounded, Fiona lives by her own odd set of rules, often delighting in strange traditions or ideas that others find baffling. She has deep empathy for all living creatures and believes in easing suffering wherever she can. While her Fey nature leaves her curious and excitable, her years of motherhood and guild service have given her a structured side — one obsessed with schedules and keeping things running smoothly. Her joy and wonder are infectious, though she can sometimes exhaust others with her wild enthusiasm for new ideas.",
            deityId: deities.selune.id,
            deityReasoning:
                "Fiona follows Selûne, Our Lady of Silver, drawing comfort from her guidance through the shifting phases of life. To Fiona, Selûne's light is a beacon in both the familiar world and the strange wilds of the Fey, a reminder that change and cycles are natural and worth embracing.",
            age: 34,
            keyAttributes: "Her deep connection to nature, her draconic bond, and her nurturing spirit as both a mother and caretaker of beasts.",
            ideals: "Harmony: All creatures, great and small, deserve respect and care; balance in nature is essential.",
            bonds: "Her Family: Fiona is overjoyed to have found love and stability with Ilikan and their son Auren, cherishing the life they have built together in a world she felt would never understand her.",
            flaws: "Seclusiveness: Fiona's whimsical nature and deep connection to the Feywild can make her seem distant or hard to understand, leading to misunderstandings with others.",
            gearLoadout: "A large keyring, a satchel of beast-tending supplies, and a finely crafted longbow adorned with draconic motifs.",
            languages: {
                connect: [
                    { id: languages.common.id },
                    { id: languages.elvish.id },
                    { id: languages.goblin.id },
                    { id: languages.draconic.id },
                    { id: languages.giant.id },
                ],
            },
            fromContinentId: continents.kuriguer.id,
            livesInTownId: towns.suetonon.id,
            creatureSizeId: creatureSizes.medium.id,
            creatureTypeId: creatureTypes.humanoid.id,
        }),
		ilikanWildfist: await db.createCharacter({
            id: 'character-ilikan-wildfist',
            name: 'Ilikan Wildfist',
            raceId: races.shifter.id,
            subraceId: subraces.shifter_beasthide_shifter.id,
            classId: classes.barbarian.id,
            subclassId: subclasses.barbarian_path_of_the_giant.id,
            backstory: "Raised in Bulsania by a clan of giants, Ilikan grew up immersed in their traditions of strength, patience, and respect for the natural world. Though smaller than his adoptive family, he carried their teachings with him, shaping his steady worldview. In his early twenties, he wandered far from home, eventually arriving in Skratonia almost by accident. There he crossed paths with Tharos, the Guild Master of the Huntbound Order, who took a keen interest in this unusual shifter with a giant's upbringing. At the time, the guild was expanding and in need of a new hall, and Tharos offered Ilikan the position of groundskeeper. Ilikan accepted, and over the years became a cornerstone of the guild's daily life. Alongside tending to the land, halls, and gardens, Ilikan earned renown within the guild as a skilled mender — sewing garments, repairing armor, and fixing tools with the same care he applies to nurturing the grounds. During his service, he met and married Fiona Mirage, the guild's Beast Master, and together they now raise their son within the safety of the guild hall. Though no longer an adventurer, Ilikan's quiet strength, resourceful hands, and devotion to both craft and family make him indispensable to the Huntbound Order.",
            gender: 'Male',
            appearance: "A sturdy shifter of 31 years, Ilikan stands 5'8” with a broad, muscular frame tempered by years of physical labor rather than battle. His hair is thick and dark, often tied back, and his beasthide features give his skin a rugged, weathered look reminiscent of stone. His eyes carry a gentle steadiness, betraying his giant upbringing through their calm depth. He dresses in simple, durable work clothes, often marked by earth, grass, or dust from tending to the guild grounds. He often wears a belt of tools for mending and repair, from sewing needles to small hammers and leather patches. Around his neck hangs a giant-made trinket, resized for him, a reminder of the family who raised him.",
            personality: "Calm, steady, and dependable, Ilikan is a man who believes in patience and the importance of steady effort. He often repeats the saying, 'Every avalanche begins as a single pebble,' a reflection of his giant-raised philosophy that great change comes from humble beginnings. While his shifter heritage gives him strength and resilience, he prefers peace over conflict, showing kindness to guild members, guests, and even the smallest of creatures on the guild's grounds. Beneath his calm demeanor, however, lies a protective spirit that will rise like a storm if those he loves are threatened. He is meticulous with his hands and takes quiet pride in repairing gear and maintaining the guild hall, believing that even worn tools and broken items deserve new life.",
            deityId: deities.lathander.id,
            deityReasoning:
                "Ilikan follows Lathander, the Morninglord, finding inspiration in the ideals of renewal, growth, and hope. To him, every sunrise is a reminder that no matter what is lost, life continues, and there is always a chance to begin again.",
            age: 31,
            keyAttributes: "His steady strength, meticulous craftsmanship in mending, and deep sense of responsibility toward the guild and his family.",
            ideals: "Patience: Great things take time, and steady effort leads to lasting change.",
            bonds: "His Family: Ilikan's greatest joy and responsibility is his family — his wife Fiona and their son Auren. They are his anchor and his motivation.",
            flaws: "Overcautiousness: Ilikan's preference for peace and patience can sometimes lead to hesitation, especially when quick action is needed.",
            gearLoadout: "A belt of mending tools, a sturdy work apron, and a small trinket from his giant family.",
            languages: {
                connect: [
                    { id: languages.common.id },
                    { id: languages.giant.id },
                    { id: languages.goblin.id },
                    { id: languages.common_sign_language.id },
                ],
            },
            fromContinentId: continents.bulsania.id,
            livesInTownId: towns.suetonon.id,
            creatureSizeId: creatureSizes.medium.id,
            creatureTypeId: creatureTypes.humanoid.id,
        }),
		aurenWildfist: await db.createCharacter({
            id: 'character-auren-wildfist',
            name: 'Auren Wildfist',
            raceId: races.changeling_shifter.id,
            classId: classes.wizard.id,
            backstory: "Born and raised in the Huntbound Order's guild hall, Auren has only ever known life surrounded by adventurers, staff, and the bustle of the guild. From a young age his intelligence was noticed, and he began studying magic under Ovlan Kalek, the Order's librarian and renowned wizard. Now apprenticing as a novice wizard, Auren shows particular interest in the ideas of graviturgy, drawn to the mysteries of weight, force, and motion. At the same time, he works as a waiter in the guild hall, where his high charisma, attention to detail, and sharp memory make him excellent at his duties. Patrons enjoy his impeccable service and genuine warmth, often rewarding him with generous tips. Fluent in Giant thanks to his father's teaching, Auren shares a close bond with Ilikan and models much of his character after him. Though only nine years old, Auren already dreams of one day becoming a wizard of renown like his mentor, while also carrying on the values of service and growth that his family instilled in him.",
            gender: 'Male',
            appearance: "Auren is a bright-eyed 9-year-old changeling shifter boy, small for his age but with a sharp presence. His default form resembles a pale-skinned youth with emerald eyes inherited from his mother, though his jet black hair and furry coat clearly reflect his father's. His face carries a hint of innocence touched by focus and determination, giving him a studious look for one so young. When concentrating on his magic, faint shimmering runes sometimes flicker across his skin, a lingering sign of his arcane studies. He dresses neatly, usually in simple a simple vest and scarf for his work as a guild waiter, often with a small satchel of books or scrolls strapped to his back.",
            personality: "Intelligent, perfectionist, and quietly ambitious, Auren is eager to prove himself both in service and study. He takes great pride in doing things right, whether it's serving food flawlessly, memorizing orders, or mastering a new spell. While naturally charming and polite with guild guests, he is often found deep in study when off-duty, showing remarkable focus for a child. He looks up to both his parents as role models and to Ovlan, the guild librarian, as his mentor. Though young, Auren already carries himself with a sense of responsibility and purpose, tempered by curiosity and a child's boundless energy.",
            deityId: deities.lathander.id,
            deityReasoning:
                "Like his father, Auren follows Lathander, the Morninglord. He views the god's ideals of renewal and growth as deeply inspiring, believing that his studies and service are part of a brighter future he is helping to build.",
            age: 9,
            keyAttributes: "His sharp intellect, dedication to service, and early mastery of arcane studies.",
            ideals: "Excellence: Strive to be the best in all you do, whether in service or study.",
            bonds: "His Family and Mentor: Auren cherishes his parents Ilikan and Fiona, as well as his mentor Ovlan, drawing strength and inspiration from their love and guidance.",
            flaws: "Perfectionism: Auren's desire to excel can sometimes lead to frustration when things don't go as planned, especially in his studies.",
            gearLoadout: "A small satchel of spell components, a neatly kept notebook for arcane studies, and a polished serving tray.",
            languages: {
                connect: [
                    { id: languages.common.id },
                    { id: languages.giant.id },
                    { id: languages.elvish.id },
                    { id: languages.vedalken.id },
                ],
            },
            fromContinentId: continents.skratonia.id,
            livesInTownId: towns.suetonon.id,
            creatureSizeId: creatureSizes.medium.id,
            creatureTypeId: creatureTypes.humanoid.id,
        }),
		keotiFang: await db.createCharacter({
            id: 'character-keoti-fang',
            name: 'Keoti Fang',
            raceId: races.tabaxi.id,
            classId: classes.paladin.id,
            subclassId: subclasses.paladin_oath_of_the_crown.id,
            backstory: "Keoti Fang was born among the wandering tabaxi clans of Skratonia, but even as a youth he saw how fragile freedom could be without protection. When his caravan was threatened by raiders, Keoti joined the defenders despite his age, using his speed and cunning to distract and mislead attackers until reinforcements arrived. The memory of standing with his people, protecting something greater than himself, never left him. Years later, when Kuriguer began pressing into the coastal cities and forests, Keoti entered the Skratonian Alliance's ranks as a scout. His natural swiftness made him ideal for reconnaissance, though he broke tradition by wielding a greataxe, learning to channel his momentum into devastating strikes while still clad in light armor. The horrors of battle scarred him, but also deepened his conviction: the strength of the many rests on the sacrifice and duty of the few. It was this belief that led him to swear the Oath of the Crown, devoting himself to law, order, and the protection of those who could not protect themselves. During long campaigns, he began to experience moonlit dreams and visions, which chaplains of Sehanine Moonbow taught him to embrace as guidance. Her teachings balanced his rigid sense of duty with hope, mystery, and the promise of renewal. After the war, Keoti was recommended by a fellow veteran to Tharos, the Huntbound Order's Guild Master who was seeking someone who could handle conflict beyond monster slaying, Tharos welcomed Keoti as the guild's House Carl. Today, Keoti serves as both protector and peacekeeper, his commanding presence enough to quell most disputes, though when force is required, a quick resolution can still be expected.",
            gender: 'Male',
            appearance: "Keoti is a lean tabaxi of 46 years. His fur is short and patterned with dark rosettes across a tawny-gold coat, and his long striped tail sways with controlled precision. His amber eyes are sharp and piercing, reflecting both keen awareness and the burden of long campaigns. A scar along his arms, and a notch from his ear missing — reminders of battles past. He wears well-kept studded leather armor fitted for mobility, and carries a massive greataxe across his back. His movements are fluid and disciplined, his stance always ready for sudden action.",
            personality: "Direct, disciplined, and slow to trust, Keoti is a soldier who has carried the lessons of war into guild life. He faces problems head-on, preferring clear, decisive action over hesitation. While slow to form new bonds, his loyalty is unshakable once earned, and he treats comradeship as sacred. Beneath his stern and laconic exterior lies a surprising depth shaped by his devotion to Sehanine Moonbow. In quiet moments, Keoti speaks of journeys as dreams given form, and sees every path as part of a greater mystery. Though most know him as a hardened warrior, those close to him glimpse a man who believes even scars are part of a larger story written in moonlight.",
            deityId: deities.sehanine_moonbow.id,
            deityReasoning:
                "Keoti follows Sehanine Moonbow, Goddess of Dreams, Journeys, and Mysteries. He views her as a guide for soldiers and wanderers alike, offering solace in the quiet of the night and meaning in the endless road of service. Her tenets of journeys and mysteries resonate with his life after war, giving him purpose beyond the battlefield.",
            age: 46,
            keyAttributes: "His disciplined combat skills, unwavering sense of duty, and the balance he finds between order and mystery through his faith.",
            ideals: "Duty: The strength of the many rests on the sacrifice and duty of the few; protect those who cannot protect themselves.",
            bonds: "The Huntbound Guild: Keoti is deeply committed to the guild's mission, seeing it as a continuation of his service and a way to protect the innocent from threats both monstrous and mundane.",
            flaws: "Rigidness: His strict adherence to duty and order can make him inflexible, sometimes struggling to adapt to situations that require nuance or compromise.",
            gearLoadout: "A massive greataxe and a locket containing a small moonstone gifted by a Sehanine priestess.",
            languages: {
                connect: [
                    { id: languages.common.id },
                    { id: languages.tabaxi.id },
                    { id: languages.orcish.id },
                    { id: languages.leonin.id },
                ],
            },
            fromContinentId: continents.skratonia.id,
            livesInTownId: towns.suetonon.id,
            creatureSizeId: creatureSizes.medium.id,
            creatureTypeId: creatureTypes.humanoid.id,
        }),
		snekLittlefoot: await db.createCharacter({
            id: 'character-snek-littlefoot',
            name: 'Snek Littlefoot',
            raceId: races.kobold.id,
            classId: classes.druid.id,
            subclassId: subclasses.druid_circle_of_the_moon.id,
            backstory: "At the age of 14, Snek was exiled from his kobold clan's cave after being accused of revealing the location of a hidden treasure hoard to a rival clan. In truth, Snek had only been repeating overheard conversations — as he often did — and never understood the importance of what he had let slip. Though innocent of intentional betrayal, the damage was done, and his clan cast him out as a traitor. Lost and alone, he wandered the forests for months until he was taken in by a wandering Circle of the Moon druid grove. Though he never fully mastered their ways, he discovered a natural gift for conversing with animals and soon became the forest's greatest gossip, gathering news from creatures near and far. One day he strayed too far and became lost in a city, where fate led him to the Huntbound Order. Though adventuring life quickly proved... not good for his health, Snek found his place caring for the guild's messenger network of birds, beasts, and magical couriers. Over time, he became the guild's seeded Fancier and Messenger, always armed with the latest tidbit of information (most of which he assumes comes from his animals' chatter). While some suspect he unknowingly runs a spy network, Snek himself is blissfully unaware, simply happy to have a home and a purpose.",
            gender: 'Male',
            appearance: "Snek is a small, wiry kobold of 21 years, standing just under 3' tall. His scales are a muted reddish-brown, flecked with lighter tan markings along his snout and tail. His yellow-green eyes are wide and expressive, always darting about as if searching for the next bit of news or gossip. A few of his teeth stick out in a perpetual crooked grin, giving him an unintentionally mischievous look. He dresses in simple but colorful tunics with patched sleeves, often carrying satchels and scroll tubes strapped to his belt for guild messages. Birds, small mammals, or trained messenger creatures are often seen perched near him, as if naturally drawn to his constant chatter.",
            personality: "Friendly, excitable, and endlessly talkative, Snek has a knack for picking up bits of information and retelling them with unshakable enthusiasm — whether or not they're accurate. He loves to quote what he claims are wise sayings from the druids who raised him, though his paraphrasing usually strips them of all meaning. Despite his eagerness, Snek is a terrible secret keeper, often spilling information without realizing it. Still, his good heart and cheerful energy make him a beloved member of the guild. He finds joy in connecting with animals and people alike, and always seems to know something new about someone.",
            deityId: deities.tymora.id,
            deityReasoning:
                "Snek follows Tymora, the Lady Luck, whom he believes has guided his strange, winding path. He views luck and chance as the reason he always stumbles into interesting news, encounters, and opportunities, trusting in her to keep his fortunes turning.",
            age: 21,
            keyAttributes: "His natural affinity for animals, his boundless enthusiasm for gossip, and his unwavering optimism.",
            ideals: "Connection: Every creature has a story, and sharing those stories brings us closer together.",
            bonds: "The Huntbound Guild: Snek is deeply grateful to the guild for giving him a home and purpose, and he dedicates himself to serving its members through his messenger duties.",
            flaws: "Loose Lips: Snek's inability to keep secrets often leads to unintended consequences, as he frequently shares information without realizing its importance.",
            gearLoadout: "A satchel of scrolls and messages, a whistle for calling messenger animals, and a small druidic charm gifted by his former grove.",
            languages: {
                connect: [
                    { id: languages.common.id },
                    { id: languages.draconic.id },
                    { id: languages.primordial.id },
                ],
            },
            fromContinentId: continents.maltman.id,
            livesInTownId: towns.suetonon.id,
            creatureSizeId: creatureSizes.small.id,
            creatureTypeId: creatureTypes.humanoid.id,
        }),
		whoWingfall: await db.createCharacter({
            id: 'character-who-wingfall',
            name: 'Who Wingfall',
            raceId: races.owlin.id,
            classId: classes.bard.id,
            backstory: "Who Wingfall inherited a lute and a song from her father upon his passing, inspiring her to pursue a life as a bard. She began performing in the streets of Suetonon, writing songs and building a small following. Tharos, recognizing her talent and dedication, offered her a position as a waitress in the Huntbound Order, with the promise she could perform in the guild's great hall during breaks from her duties. Who accepted, seeing the guild as both a home and a stage for her art being a perfect place to get tales to write about, where she could grow into the bard she dreams of becoming.",
            gender: 'Female',
            appearance: "Who is a small, owlin of 23 years, standing around 4 feet tall with a round face framed by soft, mottled brown and cream feathers. Her large golden eyes are bright and alert, and her wings fold to her back. She has a small, hooked beak and slender talons, and often wears a simple tunic with fitted sleeves that allow for ease of movement while serving or performing. A well-used lute is slung across her back, and a small satchel for sheet music is tucked at her side.",
            personality: "Determined, passionate, and a little headstrong, Who follows her dreams with single-minded focus. She is devoted to her music and inherited her father's lute and a song that has always inspired her, shaping both her ambitions and her temperament. While she can be oblivious to her own limitations at times, her dedication and enthusiasm make her a beloved presence in the guild. She is disciplined in her waitress duties but cherishes the moments she gets to perform, often bringing warmth and entertainment to the guild's members and guests.",
            deityId: deities.tymora.id,
            deityReasoning:
                "Who follows Tymora, Lady Luck, seeing her guidance in the small strokes of fortune that have brought her to the guild and allowed her to pursue her musical ambitions safely. She believes luck favors those who persistently follow their dreams.",
            age: 23,
            keyAttributes: "Her musical talent, unwavering dedication to her craft, and her ability to bring joy and entertainment to those around her.",
            ideals: "Passion: Follow your dreams with all your heart, and let your art be a beacon for others.",
            bonds: "Her Father's Legacy: Who is deeply connected to the memory of her father, cherishing the lute and song he left her as symbols of his love and inspiration.",
            flaws: "Clumsiness: Who's single-minded focus on her music sometimes leads to accidents or mishaps, especially when balancing her waitress duties with her performance aspirations.",
            gearLoadout: "A well-used lute, a satchel of sheet music, and a charm of Tymora for good luck.",
            languages: {
                connect: [
                    { id: languages.common.id },
                    { id: languages.owlin.id },
                    { id: languages.common_sign_language.id },
                ],
            },
            fromContinentId: continents.skratonia.id,
            livesInTownId: towns.suetonon.id,
            creatureSizeId: creatureSizes.medium.id,
            creatureTypeId: creatureTypes.humanoid.id,
        }),
		xandrosKirvath: await db.createCharacter({
            id: '',
            name: '',
            raceId: races..id,
            classId: classes..id,
            subclassId: subclasses..id,
            backstory: "",
            gender: '',
            appearance: "",
            personality: "",
            deityId: deities..id,
            deityReasoning:
                "",
            age: ,
            keyAttributes: "",
            ideals: "",
            bonds: "",
            flaws: "",
            gearLoadout: "",
            languages: {
                connect: [
                    { id: languages.common.id },
                ],
            },
            fromContinentId: continents..id,
            livesInTownId: towns.suetonon.id,
            creatureSizeId: creatureSizes.medium.id,
            creatureTypeId: creatureTypes.humanoid.id,
        }),
		verdiSapKnot: await db.createCharacter({
            id: '',
            name: '',
            raceId: races..id,
            classId: classes..id,
            subclassId: subclasses..id,
            backstory: "",
            gender: '',
            appearance: "",
            personality: "",
            deityId: deities..id,
            deityReasoning:
                "",
            age: ,
            keyAttributes: "",
            ideals: "",
            bonds: "",
            flaws: "",
            gearLoadout: "",
            languages: {
                connect: [
                    { id: languages.common.id },
                ],
            },
            fromContinentId: continents..id,
            livesInTownId: towns.suetonon.id,
            creatureSizeId: creatureSizes.medium.id,
            creatureTypeId: creatureTypes.humanoid.id,
        }),
		krakFrostmarchCompany: await db.createCharacter({
            id: '',
            name: '',
            raceId: races..id,
            classId: classes..id,
            subclassId: subclasses..id,
            backstory: "",
            gender: '',
            appearance: "",
            personality: "",
            deityId: deities..id,
            deityReasoning:
                "",
            age: ,
            keyAttributes: "",
            ideals: "",
            bonds: "",
            flaws: "",
            gearLoadout: "",
            languages: {
                connect: [
                    { id: languages.common.id },
                ],
            },
            fromContinentId: continents.bulsania.id,
            livesInTownId: towns.suetonon.id,
            creatureSizeId: creatureSizes.medium.id,
            creatureTypeId: creatureTypes.humanoid.id,
        }),
		sabaakFrostmarchCompany: await db.createCharacter({
            id: '',
            name: '',
            raceId: races..id,
            classId: classes..id,
            subclassId: subclasses..id,
            backstory: "",
            gender: '',
            appearance: "",
            personality: "",
            deityId: deities..id,
            deityReasoning:
                "",
            age: ,
            keyAttributes: "",
            ideals: "",
            bonds: "",
            flaws: "",
            gearLoadout: "",
            languages: {
                connect: [
                    { id: languages.common.id },
                ],
            },
            fromContinentId: continents.bulsania.id,
            livesInTownId: towns.suetonon.id,
            creatureSizeId: creatureSizes.medium.id,
            creatureTypeId: creatureTypes.humanoid.id,
        }),
		varkunTarlok: await db.createCharacter({
            id: '',
            name: '',
            raceId: races..id,
            classId: classes..id,
            subclassId: subclasses..id,
            backstory: "",
            gender: '',
            appearance: "",
            personality: "",
            deityId: deities..id,
            deityReasoning:
                "",
            age: ,
            keyAttributes: "",
            ideals: "",
            bonds: "",
            flaws: "",
            gearLoadout: "",
            languages: {
                connect: [
                    { id: languages.common.id },
                ],
            },
            fromContinentId: continents..id,
            livesInTownId: towns.suetonon.id,
            creatureSizeId: creatureSizes.medium.id,
            creatureTypeId: creatureTypes.humanoid.id,
        }),
		whisper: await db.createCharacter({
            id: '',
            name: '',
            raceId: races..id,
            classId: classes..id,
            subclassId: subclasses..id,
            backstory: "",
            gender: '',
            appearance: "",
            personality: "",
            deityId: deities..id,
            deityReasoning:
                "",
            age: ,
            keyAttributes: "",
            ideals: "",
            bonds: "",
            flaws: "",
            gearLoadout: "",
            languages: {
                connect: [
                    { id: languages.common.id },
                ],
            },
            fromContinentId: continents..id,
            livesInTownId: towns.suetonon.id,
            creatureSizeId: creatureSizes.medium.id,
            creatureTypeId: creatureTypes.humanoid.id,
        }),
		elaraMoonwhisper: await db.createCharacter({
            id: '',
            name: '',
            raceId: races..id,
            classId: classes..id,
            subclassId: subclasses..id,
            backstory: "",
            gender: '',
            appearance: "",
            personality: "",
            deityId: deities..id,
            deityReasoning:
                "",
            age: ,
            keyAttributes: "",
            ideals: "",
            bonds: "",
            flaws: "",
            gearLoadout: "",
            languages: {
                connect: [
                    { id: languages.common.id },
                ],
            },
            fromContinentId: continents.kuriguer.id,
            livesInTownId: towns.silverleaf_harbor.id,
            creatureSizeId: creatureSizes.medium.id,
            creatureTypeId: creatureTypes.humanoid.id,
        }),
		gorakSwampstrider: await db.createCharacter({
            id: '',
            name: '',
            raceId: races..id,
            classId: classes..id,
            subclassId: subclasses..id,
            backstory: "",
            gender: '',
            appearance: "",
            personality: "",
            deityId: deities..id,
            deityReasoning:
                "",
            age: ,
            keyAttributes: "",
            ideals: "",
            bonds: "",
            flaws: "",
            gearLoadout: "",
            languages: {
                connect: [
                    { id: languages.common.id },
                ],
            },
            fromContinentId: continents.katman.id,
            livesInTownId: towns.swamp_crown.id,
            creatureSizeId: creatureSizes.medium.id,
            creatureTypeId: creatureTypes.humanoid.id,
        }),
		thorneIronforge: await db.createCharacter({
            id: '',
            name: '',
            raceId: races..id,
            classId: classes..id,
            subclassId: subclasses..id,
            backstory: "",
            gender: '',
            appearance: "",
            personality: "",
            deityId: deities..id,
            deityReasoning:
                "",
            age: ,
            keyAttributes: "",
            ideals: "",
            bonds: "",
            flaws: "",
            gearLoadout: "",
            languages: {
                connect: [
                    { id: languages.common.id },
                ],
            },
            fromContinentId: continents.alatman.id,
            livesInTownId: towns.volcanic_throne.id,
            creatureSizeId: creatureSizes.medium.id,
            creatureTypeId: creatureTypes.humanoid.id,
        }),
		bronwynStonebeard: await db.createCharacter({
            id: '',
            name: '',
            raceId: races..id,
            classId: classes..id,
            subclassId: subclasses..id,
            backstory: "",
            gender: '',
            appearance: "",
            personality: "",
            deityId: deities..id,
            deityReasoning:
                "",
            age: ,
            keyAttributes: "",
            ideals: "",
            bonds: "",
            flaws: "",
            gearLoadout: "",
            languages: {
                connect: [
                    { id: languages.common.id },
                ],
            },
            fromContinentId: continents.maltman.id,
            livesInTownId: towns.deepforge_citadel.id,
            creatureSizeId: creatureSizes.medium.id,
            creatureTypeId: creatureTypes.humanoid.id,
        }),
		marcusGoldfield: await db.createCharacter({
            id: '',
            name: '',
            raceId: races..id,
            classId: classes..id,
            subclassId: subclasses..id,
            backstory: "",
            gender: '',
            appearance: "",
            personality: "",
            deityId: deities..id,
            deityReasoning:
                "",
            age: ,
            keyAttributes: "",
            ideals: "",
            bonds: "",
            flaws: "",
            gearLoadout: "",
            languages: {
                connect: [
                    { id: languages.common.id },
                ],
            },
            fromContinentId: continents.skratonia.id,
            livesInTownId: towns.golden_fields.id,
            creatureSizeId: creatureSizes.medium.id,
            creatureTypeId: creatureTypes.humanoid.id,
        }),
		thaneIcewind: await db.createCharacter({
            id: '',
            name: '',
            raceId: races..id,
            classId: classes..id,
            subclassId: subclasses..id,
            backstory: "",
            gender: '',
            appearance: "",
            personality: "",
            deityId: deities..id,
            deityReasoning:
                "",
            age: ,
            keyAttributes: "",
            ideals: "",
            bonds: "",
            flaws: "",
            gearLoadout: "",
            languages: {
                connect: [
                    { id: languages.common.id },
                ],
            },
            fromContinentId: continents.bulsania.id,
            livesInTownId: towns.frosthold.id,
            creatureSizeId: creatureSizes.medium.id,
            creatureTypeId: creatureTypes.humanoid.id,
        }),
	};
}